apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: yankogp/final_project:0c290ac1473f7bf80cf92481925d36b9337e5513
          imagePullPolicy: Always
          ports:
            - containerPort: 80
