apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: yankogp/final_project:835f3f3fba907c2026968e7c143f689e4e9ceba5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
