apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: yankogp/final_project:d05ebdebad8692037cfbf0707e9d619f13af16fb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
