apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: yankogp/final_project:9dfca2ae80d0311aaf4bc8af9abefa37db385b0b
          imagePullPolicy: Always
          ports:
            - containerPort: 80
