apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: yankogp/final_project:e74242fb6c84422388dfa66c2287effa50850614
          imagePullPolicy: Always
          ports:
            - containerPort: 80
