apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: yankogp/final_project:56af44905f6f939fa097d959e4e8f757137663fb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
