apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: yankogp/final_project:f7c659bb93a2874b5d37baaaa2df720b48a92d54
          imagePullPolicy: Always
          ports:
            - containerPort: 80
