apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: yankogp/final_project:d38b69c9e44638df37f6a1a4c9b524d030bb3d61
          imagePullPolicy: Always
          ports:
            - containerPort: 80
